<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>ai.wanaku</groupId>
        <artifactId>parent</artifactId>
        <version>0.3.0-SNAPSHOT</version>
        <relativePath>../../../parent/pom.xml</relativePath>
    </parent>
    <artifactId>wanaku-debugger-plugin</artifactId>
    <packaging>pom</packaging>
    <name>Wanaku :: Deployment Debugger Plugin</name>
    <properties>
        <skipUI>false</skipUI>
    </properties>
    <build>
        <plugins>
            <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>${frontend-maven-plugin.version}</version>
                <configuration>
                    <workingDirectory>${project.basedir}</workingDirectory>
                    <installDirectory>${project.build.directory}/frontend</installDirectory>
                    <skip>${skipUI}</skip>
                </configuration>
                <executions>
                    <execution>
                        <id>install-node-and-yarn</id>
                        <phase>generate-resources</phase>
                        <goals><goal>install-node-and-yarn</goal></goals>
                        <configuration>
                            <nodeVersion>${nodejs.version}</nodeVersion>
                            <yarnVersion>${yarn.version}</yarnVersion>
                        </configuration>
                    </execution>
                    <execution>
                        <id>yarn-install</id>
                        <phase>generate-resources</phase>
                        <goals><goal>yarn</goal></goals>
                        <configuration><arguments>install --frozen-lockfile</arguments></configuration>
                    </execution>
                    <execution>
                        <id>yarn-build-plugin</id>
                        <phase>generate-resources</phase>
                        <goals><goal>yarn</goal></goals>
                        <configuration><arguments>run build:plugin</arguments></configuration>
                    </execution>
                    <execution>
                        <id>yarn-test</id>
                        <phase>test</phase>
                        <goals><goal>yarn</goal></goals>
                        <configuration>
                            <arguments>test</arguments>
                            <skip>${skipTests}</skip>
                        </configuration>
                    </execution>
                    <execution>
                        <id>yarn-lint</id>
                        <phase>verify</phase>
                        <goals><goal>yarn</goal></goals>
                        <configuration><arguments>lint</arguments></configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>dist</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-assembly-plugin</artifactId>
                        <version>${maven-assembly-plugin.version}</version>
                        <configuration>
                            <attach>false</attach>
                            <appendAssemblyId>false</appendAssemblyId>
                            <outputDirectory>${distribution.directory}</outputDirectory>
                            <finalName>${project.artifactId}-${project.version}</finalName>
                            <descriptors><descriptor>src/main/assembly/plugin.xml</descriptor></descriptors>
                        </configuration>
                        <executions>
                            <execution>
                                <id>make-plugin-distribution</id>
                                <phase>package</phase>
                                <goals><goal>single</goal></goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
