/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */

export type GetApiV1DataStoreGetParams = {
  id?: string;
  name?: string;
};
