/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { SemanticExpertOperationParameterSchema } from "./semanticExpertOperationParameterSchema";

export interface SemanticExpertOperation {
  /**
   * Native operation name
   * @pattern [A-Za-z][A-Za-z0-9_-]{0,63}
   */
  name: string;
  /**
   * Supported input kinds, for example text
   * @minItems 1
   * @maxItems 16
   */
  inputTypes: string[];
  /**
   * Native result kind, for example choice or boolean
   * @maxLength 64
   * @pattern \S
   */
  resultType: string;
  /**
   * Human-readable meaning of the result
   * @maxLength 512
   */
  resultMeaning?: string;
  /** Draft-07 JSON Schema for operation parameters, without external references */
  parameterSchema?: SemanticExpertOperationParameterSchema;
}
