/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */

/**
 * Draft-07 JSON Schema for operation parameters, without external references
 */
export type SemanticExpertOperationParameterSchema = { [key: string]: unknown };
