/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */

/**
 * Expect guard rejection instead of classification; absent means false
 */
export type SemanticExampleExpectedBlocked = boolean | null;
