/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { SemanticResolvedPublicationGuardAnyOf } from "./semanticResolvedPublicationGuardAnyOf";

/**
 * Guard configuration captured in the selected publication
 */
export type SemanticResolvedPublicationGuard =
  SemanticResolvedPublicationGuardAnyOf | null;
