/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { SemanticPublishedGuard } from "./semanticPublishedGuard";

/**
 * Guard configuration captured in the selected publication
 */
export type SemanticResolvedPublicationGuardAnyOf =
  SemanticPublishedGuard | null;
