/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { SemanticPublishedGuard } from "./semanticPublishedGuard";

/**
 * Immutable guard configuration and expert snapshot
 */
export type SemanticPublicationGuard = SemanticPublishedGuard | null;
