/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { SemanticPreviewGuardAnyOf } from "./semanticPreviewGuardAnyOf";

/**
 * Guard verdict; absent when disabled or failed
 */
export type SemanticPreviewGuard = SemanticPreviewGuardAnyOf | null;
