/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { SemanticGuard } from "./semanticGuard";

/**
 * Optional Boolean guard evaluated before classification
 */
export type SemanticRouterDefinitionGuardAnyOf = SemanticGuard | null;
