/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { SemanticGuardPreviewDiagnostics } from "./semanticGuardPreviewDiagnostics";

export interface SemanticGuardPreview {
  value?: boolean;
  diagnostics?: SemanticGuardPreviewDiagnostics;
}
