/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */

export interface ServiceTemplateSystem {
  name?: string;
  routesFile?: string;
  rulesFile?: string;
  dependenciesFile?: string;
  propertiesFile?: string;
}
