/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { CapabilityStatistics } from "./capabilityStatistics";

export interface SystemStatistics {
  serviceCatalogsCount?: number;
  serviceTemplatesCount?: number;
  toolsetReposCount?: number;
  dataStoresCount?: number;
  toolCapabilities?: CapabilityStatistics;
  resourceCapabilities?: CapabilityStatistics;
}
