# HTTP Server Configuration
quarkus.http.host-enabled=true
quarkus.http.port=9000
quarkus.http.host=0.0.0.0

quarkus.banner.enabled = false
quarkus.devservices.enabled = false
quarkus.console.enabled = false

quarkus.log.level=WARNING
quarkus.log.category."ai.wanaku".level=INFO
%dev.quarkus.log.category."ai.wanaku".level=DEBUG
%test.quarkus.log.category."ai.wanaku".level=INFO

wanaku.service.name=http

# Registration settings
#wanaku.service.registration.uri=http://localhost:8080
#wanaku.service.registration.interval=10s
#wanaku.service.registration.retry-wait-seconds=1
#wanaku.service.registration.retries=3
#wanaku.service.registration.delay-seconds=3
#wanaku.service.registration.announce-address=my-custom-addr
